/// A default empty routing rule part of the test production for testing the InterfaceDiskSpaceframework. 
/// <br>See <class>InterfaceDiskSpace.Main</class> for details on the framework and/or <class>InterfaceDiskSpace.Test.Prod.TestProduction</class> about the test production
Class InterfaceDiskSpace.Test.Prod.RecordRouterRoutingRule Extends Ens.Rule.Definition
{

Parameter RuleAssistClass = "EnsLib.MsgRouter.RuleAssist";

XData RuleDefinition [ XMLNamespace = "http://www.intersystems.com/rule" ]
{
<ruleDefinition alias="InterfaceDiskSpace.Test.Prod.Record RouterRoutingRule" context="EnsLib.MsgRouter.RoutingEngine" production="InterfaceDiskSpace.Test.Prod.TestProduction">
<ruleSet name="" effectiveBegin="" effectiveEnd="">
<rule name="">
</rule>
</ruleSet>
</ruleDefinition>
}

}
